# P6Spy ??
# ?????????
logMessageFormat=io.github.faustofan.admin.config.P6SpyMessageFormatter
# ?? SLF4J ????
appender=com.p6spy.engine.spy.appender.Slf4JLogger
# ????
excludecategories=info,debug,result,resultset,batch
# ??????
autoflush=true

