-- liquibase formatted sql

-- changeset faustofan:001-initial-schema-pg

-- 1. 租户表
CREATE TABLE sys_tenant (
    -- PG/H2 兼容的自增写法
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            deleted BOOLEAN NOT NULL DEFAULT FALSE,

                            name VARCHAR(50) NOT NULL,
                            code VARCHAR(50) NOT NULL,
                            contact_name VARCHAR(50),
                            status VARCHAR(20) NOT NULL,
                            expire_time TIMESTAMP,

                            CONSTRAINT uk_sys_tenant_code UNIQUE (code)
);

-- 2. 组织表
CREATE TABLE sys_org (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         deleted BOOLEAN NOT NULL DEFAULT FALSE,
                         tenant_id VARCHAR(50) NOT NULL,

                         name VARCHAR(50) NOT NULL,
                         parent_id BIGINT,

                         org_id BIGINT,
                         created_by VARCHAR(64) NOT NULL
);
CREATE INDEX idx_sys_org_parent ON sys_org(parent_id);

-- 3. 菜单表
CREATE TABLE sys_menu (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          deleted BOOLEAN NOT NULL DEFAULT FALSE,
                          tenant_id VARCHAR(50) NOT NULL,

                          title VARCHAR(50) NOT NULL,
                          parent_id BIGINT,
                          type VARCHAR(20) NOT NULL,
                          path VARCHAR(255),
                          component VARCHAR(255),
                          permission VARCHAR(100),
                          icon VARCHAR(50),
                          sort_order INT NOT NULL DEFAULT 0
);
CREATE INDEX idx_sys_menu_parent ON sys_menu(parent_id);

-- 4. 权限表
CREATE TABLE sys_permission (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                deleted BOOLEAN NOT NULL DEFAULT FALSE,
                                tenant_id VARCHAR(50) NOT NULL,

                                code VARCHAR(100) NOT NULL,
                                name VARCHAR(50) NOT NULL,
                                group_name VARCHAR(50),
                                description VARCHAR(255),

                                CONSTRAINT uk_sys_permission_code UNIQUE (tenant_id, code)
);

-- 5. 角色表
CREATE TABLE sys_role (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          deleted BOOLEAN NOT NULL DEFAULT FALSE,
                          tenant_id VARCHAR(50) NOT NULL,

                          code VARCHAR(50) NOT NULL,
                          name VARCHAR(50) NOT NULL,
                          description VARCHAR(255),
                          data_scope VARCHAR(20) NOT NULL DEFAULT 'SELF',

                          CONSTRAINT uk_sys_role_code UNIQUE (tenant_id, code)
);

-- 6. 用户表
CREATE TABLE SYS_USER (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          deleted BOOLEAN NOT NULL DEFAULT FALSE,
                          tenant_id VARCHAR(50) NOT NULL,

                          username VARCHAR(64) NOT NULL,
                          nickname VARCHAR(64),
                          password_hash VARCHAR(100) NOT NULL,
                          email VARCHAR(100),
                          phone VARCHAR(20),
                          avatar VARCHAR(255),
                          status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

                          org_id BIGINT,
                          created_by VARCHAR(64) NOT NULL,

                          CONSTRAINT uk_sys_user_username UNIQUE (tenant_id, username)
);
CREATE INDEX idx_sys_user_org ON sys_user(org_id);

-- 7. 关联表 (中间表)
CREATE TABLE sys_role_menu_mapping (
                                       role_id BIGINT NOT NULL,
                                       menu_id BIGINT NOT NULL,
                                       PRIMARY KEY (role_id, menu_id)
);

CREATE TABLE sys_role_permission_mapping (
                                             role_id BIGINT NOT NULL,
                                             permission_id BIGINT NOT NULL,
                                             PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE sys_role_org_mapping (
                                      role_id BIGINT NOT NULL,
                                      org_id BIGINT NOT NULL,
                                      PRIMARY KEY (role_id, org_id)
);

CREATE TABLE sys_user_role_mapping (
                                       user_id BIGINT NOT NULL,
                                       role_id BIGINT NOT NULL,
                                       PRIMARY KEY (user_id, role_id)
);

-- 8. 外键
ALTER TABLE sys_org ADD CONSTRAINT fk_sys_org_parent FOREIGN KEY (parent_id) REFERENCES sys_org(id);
ALTER TABLE sys_menu ADD CONSTRAINT fk_sys_menu_parent FOREIGN KEY (parent_id) REFERENCES sys_menu(id);
ALTER TABLE sys_user ADD CONSTRAINT fk_sys_user_org FOREIGN KEY (org_id) REFERENCES sys_org(id);

ALTER TABLE sys_role_menu_mapping ADD CONSTRAINT fk_rm_role FOREIGN KEY (role_id) REFERENCES sys_role(id) ON DELETE CASCADE;
ALTER TABLE sys_role_menu_mapping ADD CONSTRAINT fk_rm_menu FOREIGN KEY (menu_id) REFERENCES sys_menu(id) ON DELETE CASCADE;

ALTER TABLE sys_role_permission_mapping ADD CONSTRAINT fk_rp_role FOREIGN KEY (role_id) REFERENCES sys_role(id) ON DELETE CASCADE;
ALTER TABLE sys_role_permission_mapping ADD CONSTRAINT fk_rp_perm FOREIGN KEY (permission_id) REFERENCES sys_permission(id) ON DELETE CASCADE;

ALTER TABLE sys_role_org_mapping ADD CONSTRAINT fk_ro_role FOREIGN KEY (role_id) REFERENCES sys_role(id) ON DELETE CASCADE;
ALTER TABLE sys_role_org_mapping ADD CONSTRAINT fk_ro_org FOREIGN KEY (org_id) REFERENCES sys_org(id) ON DELETE CASCADE;

ALTER TABLE sys_user_role_mapping ADD CONSTRAINT fk_ur_user FOREIGN KEY (user_id) REFERENCES sys_user(id) ON DELETE CASCADE;
ALTER TABLE sys_user_role_mapping ADD CONSTRAINT fk_ur_role FOREIGN KEY (role_id) REFERENCES sys_role(id) ON DELETE CASCADE;